name = "labmu-cms-dev"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[[d1_databases]]
binding = "DB"
database_name = "nama-db"
database_id = "id-db"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "nama-bucket"

# --- CONFIG KV CACHE QURAN ---
[[kv_namespaces]]
binding = "nama-kv"
id = "id-kv"